@milestone_web_1 @rlhf @history @dpo @angular @web
Feature: RLHF Panel — AI Interaction History

  As an administrator
  I want to review, rate, and comment on the routines generated by the local AI
  So that high-quality preference pairs can be collected for future DPO training

  Background:
    Given the administrator is on the "/history" route of the Web Portal
    And the portal is configured with the "Dark Anatomy" theme

  Scenario: Load the AI interaction history successfully
    Given the AI interaction API returns a list of generated routines
    When the "/history" page loads
    Then a loading indicator is shown while the request is in flight
    And each interaction is rendered as a card with its prompt, model, and generated response
    And the interactions are sorted by creation date, newest first
    And the page shows the total number of interactions

  Scenario: Show an empty state when no interactions exist
    Given the AI interaction API returns an empty list
    When the "/history" page loads
    Then an empty state message is displayed
    And no interaction cards are rendered

  Scenario: Show an error state when the history request fails
    Given the AI interaction API is unreachable
    When the "/history" page loads
    Then an error state with a "Retry" action is displayed
    And no interaction cards are rendered
    When the administrator clicks "Retry"
    Then the history request is performed again
    And the cards are rendered if the request now succeeds

  Scenario: Rate an interaction thumbs up
    Given at least one interaction is displayed
    When the administrator clicks the thumbs up button on an interaction
    Then the interaction is marked as "positive" locally and immediately
    And a rating request is sent to the API
    And the thumbs up button is shown as active

  Scenario: Rate an interaction thumbs down
    Given at least one interaction is displayed
    When the administrator clicks the thumbs down button on an interaction
    Then the interaction is marked as "negative" locally and immediately
    And a rating request is sent to the API
    And the thumbs down button is shown as active

  Scenario: Change an existing rating
    Given an interaction is already rated "positive"
    When the administrator clicks the thumbs down button on that interaction
    Then the interaction rating changes to "negative"
    And a new rating request is sent to the API

  Scenario: Rating submission failure reverts to the previous value
    Given the rating API returns a server error
    When the administrator clicks a rating button
    Then the interaction rating is reverted to its previous value
    And an error message is displayed
    And the interaction remains visible

  Scenario: Rating buttons are disabled during submission
    Given a rating request for an interaction is in flight
    When the administrator clicks another rating button on the same interaction
    Then the rating buttons for that interaction are disabled
    And no additional rating request is sent

  Scenario: Submit written feedback via the form
    Given at least one interaction is displayed
    When the administrator expands the feedback form of an interaction
    And enters written feedback about the generated routine
    And clicks "Submit Feedback"
    Then the feedback is saved to the API
    And a success confirmation is displayed
    And the feedback text is displayed on the interaction card as previously saved

  Scenario: Reject empty feedback
    Given the feedback form of an interaction is open
    When the administrator clicks "Submit Feedback" without entering any text
    Then the form is marked as invalid
    And the "Feedback required" validation message is shown
    And no feedback request is sent

  Scenario: Feedback submission failure preserves the entered text
    Given the feedback API returns a server error
    When the administrator submits feedback with written text
    Then an error message is displayed
    And the feedback form keeps the entered text so it can be retried

  Scenario: Edit previously saved feedback
    Given an interaction has saved feedback
    When the administrator opens its feedback form
    Then the form is pre-filled with the saved feedback
    When the administrator replaces the text and submits
    Then the feedback is updated in the API
    And the new text is shown on the card