name: Mobile CD

on:
  push:
    branches: [main]
    paths:
      - 'mobile_app/**'

jobs:
  test:
    name: CI - Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test

  build:
    name: CD - Deployment
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./mobile_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: mobile_app/build/app/outputs/flutter-apk/*-release.apk
          retention-days: 30
